name: CMake

on:
 push:
   tags:
     - 'v*.*.*.*'

jobs: 

  build-project:

    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.2
      with:
         persist-credentials: false

    - name: Initialize and Update Submodules
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        git submodule update --init --recursive --jobs 8
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: CoR 1
      run: cmake -B build
      
    - name: CoR 2
      run: cmake --build build
    - name: CoR 3
      run: cmake --build build --target package
    - name: CoR 4
      run: cmake --build build --target package_source

    - name: Make a release
      uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: "build/*.deb,build/*.rpm,build/*.tar.gz,build/*.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
